<a href="https://colab.research.google.com/github/LongNguyen1984/DeepLearning/blob/master/imageColorDetect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

import torch
import imageio
import numpy as np


img_arg = imageio.imread('Mydata/Red.jpg')
img_arg1 = imageio.imread('Green1.jpg')
img_arg.size, img_arg.shape, img_arg.dtype
#using .copy() to avoid stride negatie value
img_t = torch.from_numpy(img_arg.copy())
#img_arg.strides 
#test = img_arg > 100
#test.dtype, test.sum()
img_arg.__array_interface__, img_arg1.__array_interface__,


({'data': (96905344, False),
  'descr': [('', '|u1')],
  'shape': (640, 480, 3),
  'strides': (3, -1920, 1),
  'typestr': '|u1',
  'version': 3},
 {'data': (100098048, False),
  'descr': [('', '|u1')],
  'shape': (480, 640, 3),
  'strides': None,
  'typestr': '|u1',
  'version': 3})

In [137]:
import os

batch_size = 10
batch = torch.zeros(10, 3, 640, 480, dtype=torch.uint8)

data_dir = 'Mydata/'
filenames = [name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == '.jpg']
filenames

['Red2.jpg',
 'Red.jpg',
 'Red4.jpg',
 'Blue.jpg',
 'Green2 .jpg',
 'Green.jpg',
 'Blue2.jpg',
 'Red3.jpg']

In [0]:
for i, filename in enumerate(filenames):
  img_arr = imageio.imread(os.path.join(data_dir, filename))
  img_t = torch.from_numpy(img_arr.copy())
  img_t = img_t.permute(2, 0, 1)
  img_t = img_t[:3]
  batch[i] = img_t
  

In [145]:
batch[7]

tensor([[[149., 193., 201.,  ..., 195., 165., 177.],
         [173., 245., 231.,  ..., 159., 178., 181.],
         [245., 254., 255.,  ..., 179., 178., 167.],
         ...,
         [ 40.,  41.,  41.,  ..., 255., 255., 255.],
         [ 39.,  39.,  41.,  ..., 255., 255., 255.],
         [ 39.,  39.,  39.,  ..., 255., 255., 255.]],

        [[ 16.,  51.,  54.,  ...,  85.,  56.,  68.],
         [ 46., 112.,  93.,  ...,  49.,  69.,  72.],
         [116., 125., 136.,  ...,  69.,  69.,  58.],
         ...,
         [ 14.,  15.,  15.,  ..., 245., 245., 245.],
         [ 14.,  14.,  15.,  ..., 245., 245., 245.],
         [ 14.,  14.,  14.,  ..., 245., 245., 245.]],

        [[ 37.,  75.,  80.,  ..., 114.,  85.,  97.],
         [ 65., 133., 116.,  ...,  78.,  98., 101.],
         [136., 145., 156.,  ...,  98.,  98.,  87.],
         ...,
         [ 17.,  18.,  18.,  ..., 220., 220., 220.],
         [ 17.,  17.,  18.,  ..., 220., 220., 220.],
         [ 17.,  17.,  17.,  ..., 220., 220., 220.]]]

In [0]:
#normal lize data images
batch = batch.float()
batch /=255.0


In [0]:
n_channels = batch.shape[1]
means = np.zeros(batch_size)
stds = np.zeros(batch_size)
for c in range(n_channels):
  mean = torch.mean(batch[:, c])
  means[c] = mean
  std = torch.std(batch[:, c])
  stds[c] = std
  batch[:, c] = (batch[:, c] - mean) / std

In [147]:
means , stds


(array([0.44048196, 0.30501676, 0.28940129, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]),
 array([0.34404677, 0.31353411, 0.24589187, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]))

In [157]:
batch[:,:,1].shape

torch.Size([10, 3, 480])

In [158]:
img_mean = np.zeros(batch_size)
for i in range(batch_size):
 img_mean[i] = torch.mean(batch[i])

filenames, img_mean

(['Red2.jpg',
  'Red.jpg',
  'Red4.jpg',
  'Blue.jpg',
  'Green2 .jpg',
  'Green.jpg',
  'Blue2.jpg',
  'Red3.jpg'],
 array([ 0.38049492,  0.40471682,  0.42150396,  0.44228148,  0.60769951,
         0.4573001 ,  0.29742435,  0.43822178, -0.00448356, -0.00448356]))

In [162]:
n_channels = batch.shape[1]
means = np.zeros((batch_size, n_channels))
for i in range(batch_size):
  for c in range(n_channels):
    means[i,c] = torch.mean(batch[i,c])
filenames, means  

(['Red2.jpg',
  'Red.jpg',
  'Red4.jpg',
  'Blue.jpg',
  'Green2 .jpg',
  'Green.jpg',
  'Blue2.jpg',
  'Red3.jpg'],
 array([[ 0.57404929,  0.2865119 ,  0.28088257],
        [ 0.71674198,  0.25741708,  0.24009438],
        [ 0.80554676,  0.19138214,  0.26761603],
        [ 0.41066438,  0.4390097 ,  0.47718659],
        [ 0.6443339 ,  0.72085959,  0.45775092],
        [ 0.32717112,  0.67579567,  0.36901465],
        [ 0.22784866,  0.21142176,  0.4530063 ],
        [ 0.69846368,  0.26776963,  0.34846145],
        [-0.00502039, -0.00381478, -0.00461571],
        [-0.00502039, -0.00381478, -0.00461571]]))